name: cmc
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py39hb9d737c_1004
  - bzip2=1.0.8=h7f98852_4
  - ca-certificates=2022.9.24=ha878542_0
  - certifi=2022.9.24=pyhd8ed1ab_0
  - cffi=1.14.6=py39he32792d_0
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=37.0.2=py39hd97740a_0
  - cudatoolkit=11.6.0=hecad31d_10
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.10.4=h0708190_1
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.2.0=hf544144_3
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py39h7e14d7c_0
  - mkl_fft=1.3.1=py39h0c7bc48_1
  - mkl_random=1.2.2=py39hde0f152_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - numpy=1.23.1=py39h6c91a56_0
  - numpy-base=1.23.1=py39ha15fc14_0
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h780b84a_0
  - openjpeg=2.4.0=hb52868f_1
  - openmesh-python=1.2.1=py39h1832856_2
  - openssl=1.1.1q=h7f8727e_0
  - pillow=8.2.0=py39hf95b381_1
  - pip=22.2.2=py39h06a4308_0
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=22.0.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.13=haa1d7c7_1
  - python_abi=3.9=2_cp39
  - pytorch=1.12.1=py3.9_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=pyhd8ed1ab_1
  - setuptools=63.4.1=py39h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.1=py39_cu116
  - torchvision=0.13.1=py39_cu116
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022c=h04d1e81_0
  - urllib3=1.26.11=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.0=ha95c52a_0
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - cachetools==5.2.0
    - contourpy==1.0.5
    - cycler==0.11.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.49.1
    - h5py==3.7.0
    - importlib-metadata==5.0.0
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.1
    - multidict==6.0.2
    - oauthlib==3.2.1
    - packaging==21.3
    - potpourri3d==0.0.8
    - prettytable==3.4.1
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - requests-oauthlib==1.3.1
    - robust-laplacian==0.2.4
    - rsa==4.9
    - scikit-learn==1.1.2
    - scipy==1.9.2
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - threadpoolctl==3.1.0
    - torch-cluster==1.6.0
    - torch-geometric==2.0.3
    - torch-scatter==2.0.9
    - torch-sparse==0.6.15
    - torch-spline-conv==1.2.1
    - tqdm==4.64.1
    - trimesh==3.15.3
    - vtk==9.2.2
    - wcwidth==0.2.5
    - werkzeug==2.2.2
    - wslink==1.8.2
    - yarl==1.8.1
    - zipp==3.9.0
